Audit code style
slack-samples/deno-simple-survey pull request #15
Opened 2023-04-25 18:17 UTC by WilliamBergamin

### Type of change (place an x in the [ ] that applies)

- [ ] New sample
- [ ] New feature
- [x] Bug fix
- [x] Documentation

### Summary

This PR aims to improve the Sample as part of the sample audit operation

Notable changes:
- Opted to pass the "google client id" value through environment variables instead of hard coding it.
    - This introduces a `.env` file to the project
- Moved the trigger `files` used to dynamically create triggers out of the `/triggers` folder to prevent them from appearing in the CLI trigger creation prompt (we don't want users to create these triggers manually)
-  Opted for `try/catch` pattern over return error and response
- Updated the README.md to follow the new pattern

Areas of improvement in the near future:
- When https://github.com/slackapi/deno-slack-api/pull/69 lands this sample will be able to take advantage of the new features
- Dynamic trigger creation process
- Add unit tests

Test: 
- this was manually tested

Looking for feedback on the overall flow of the developer experience and any feedback on the changes

### Requirements 

- [x] I’ve checked my submission against the Samples Checklist to ensure it complies with all standards
- [x] I have ensured the changes I am contributing align with existing patterns and have tested and linted my code
- [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct)

2023-04-25 18:36 UTC, misscoded requested changes
Thanks for taking the time to be so thorough in your review and update! 🙇🏼‍♀️ 

I leave the code changes' review up to @e-zim but in terms of the README, there were a lot of updates that I just merged in that were in an outstanding PR.

If we can just incorporate only what is necessary (spelling errors, for example), we'd generally  like to keep everything as is unless you think we've missed something big for this particular sample that would aid understanding.

2023-04-25 20:52 UTC, WilliamBergamin commented
@misscoded thanks for taking a look at the `README.md` 💯  I don't mind taking back most of my changes but I'd like to get your opinion on the following

- The [save client secret](https://github.com/slack-samples/deno-simple-survey#save-the-client-secret) step was failing on my local since the app was not installed, I added a step to execute `slack run` before this step but it seems to be a chicken and egg situation, not sure what she should do about it.
- `ClientId` is now passed through environment variables instead of hard coded I think my changes in [set the client id](https://github.com/slack-samples/deno-simple-survey#set-the-client-id) should remain.

2023-04-25 21:37 UTC, misscoded commented
@WilliamBergamin That all sounds very reasonable! I'll re-review once the changes are made, but both cases sound like they should be adjusted. I don't mind changes in the app-specific instructions; it's really the rest of the boilerplate copy and organization that I'll be really reluctant to alter

2023-04-26 17:38 UTC, misscoded approved these changes
Made some required suggestions to the README, but once those are incorporated, LGTM 🚀  Code change approval is up to @e-zim

2023-04-26 17:38 UTC, misscoded commented on README.md
> +  - [Resources](#resources)
```suggestion
- [Included Workflows](#included-workflows)
- [Setup](#setup)
  - [Install the Slack CLI](#install-the-slack-cli)
  - [Clone the Sample App](#clone-the-sample-app)
  - [Prepare Google Services](#prepare-google-services)
- [Running Your Project Locally](#running-your-project-locally)
- [Creating Triggers](#creating-triggers)
- [Datastores](#datastores)
- [Testing](#testing)
- [Deploying Your App](#deploying-your-app)
- [Viewing Activity Logs](#viewing-activity-logs)
- [Project Structure](#project-structure)
- [Resources](#resources)
```

2023-04-26 17:38 UTC, misscoded commented on README.md
> +#### Validate your app
```suggestion
#### Validate Your App
```

2023-04-26 17:38 UTC, misscoded commented on functions/configure_events.ts
>   * https://api.slack.com/future/functions/custom
```suggestion
 * https://api.slack.com/future/automation/custom
```

Can you make sure all of these `/future/` references are switched to `/automation/`?

2023-04-26 19:38 UTC, WilliamBergamin commented on functions/configure_events.ts
>   * https://api.slack.com/future/functions/custom
Done 🟢

2023-04-26 22:40 UTC, e-zim reviewed
Really appreciate all of the improvements to the code and typo corrections here @WilliamBergamin! 🙇 There's so many good code changes.

I'm going to try these changes out myself before approving – I'm currently facing a permission error when trying to `external-auth add` – but wanted to share a few comments now. None are blocking so please feel free to ignore them!

2023-04-26 22:40 UTC, e-zim commented on README.md
> +the `slack env add` command for [deployed apps](#deploying-your-app).
This wording is slightly confusing to me with my current idea of how environment variables work... Is it correct that the environment variable is automatically used in the deployment step?

2023-04-26 22:40 UTC, e-zim commented on .env.example
> +GOOGLE_CLIENT_ID=12345-example
```suggestion
# Environment variables needed to run your app. Move this file to .env to start!

# The client ID for your Google app
GOOGLE_CLIENT_ID=12345-example.apps.googleusercontent.com
```

Disregard any or all of this if you'd like! Just adding because I think some comments could be helpful (and can be easily deleted by the developer), and having a more verbose example might help clarify what value is expected here.

2023-04-26 22:40 UTC, e-zim commented on external_auth/google_provider.ts
> +}
Curious if this error message is _required_ or just a nice check to include? With both `run` and `deploy` without this environment variable set, I find the following error message:

<img width="658" alt="Screenshot 2023-04-26 at 3 15 32 PM" src="https://user-images.githubusercontent.com/18134219/234714803-ca1db7a4-357f-41d8-be6f-fc08d8e26f5b.png">

(Regardless, I think this error message is descriptive enough! Slightly unfortunate that we can't suggest our own remediation step here though...)

2023-04-26 22:40 UTC, e-zim commented on functions/utils/errors.ts
Ahhh this class and function is slightly cryptic to me. I have a general idea of the purpose, but am not sure of how it's being accomplished (with both the `super` in the constructor and `is`/`instanceof` in the function return type).

It seems like standard Typescript, so no opposition to including it, but could we include a comment to explain the purpose or reasoning?

2023-04-27 14:44 UTC, WilliamBergamin commented on README.md
> +the `slack env add` command for [deployed apps](#deploying-your-app).
This environment variable is only used to define the trigger in the `manifest` it will only be used when the CLI update the `manifest` before deploying the app, the env var will not be used at runtime, aka wont be required on ROSI

I think we could remove this note, it explains how "magic" works and could lead to confusion

Lmk what you think @e-zim

2023-04-27 14:49 UTC, WilliamBergamin commented on external_auth/google_provider.ts
> +}
This is not required, I will remove it, it was to add more clarification but the `dotenv/load.ts` library keeps surprising me 🥇

2023-04-27 15:04 UTC, WilliamBergamin commented on functions/utils/errors.ts
I think I've been living and breathing in the typescript world a bit to heavily, I agree that this can seem cryptic looking back at t now 😅 

I think leaving it in may allow some devs to look into this stuff and learn, but I will add comments to explain what is happening

2023-04-28 01:08 UTC, e-zim commented on README.md
> +the `slack env add` command for [deployed apps](#deploying-your-app).
Ah I believe that makes sense![^1] I'm in favor of including this note since otherwise I would assume that this has to be added via `slack env add`.

I also think explicitly explaining that it's used while building the manifest and is not dependent on the app environment (or used at runtime) could be helpful to note. You're getting at a good point re: the magical nuance here too. This behavior might be worthwhile to also document somewhere else, though I'm not sure where might be best... 🤔

[^1]: I'm realizing my mental model of how apps are bundled and deployed is somewhat simple; I was imagining all of the code is deployed as-is and these variables would be set on each invocation! 🤦

2023-04-28 01:09 UTC, e-zim commented on functions/utils/errors.ts
No such thing as too much Typescript! 😝 Really appreciate the explanation you've added too! You've helped me learn something new today 😁

2023-04-28 01:31 UTC, e-zim approved these changes
So many improvements to the code quality here, it's all so great. Thank you! 🙌 🏆

Tested this both locally and deployed, and things are working well. It happens that the permission error I was facing was due to the wifi I was using!

I also noticed that an empty `comment` will cause the workflow to fail, but this is already noted in #8 and not caused by this PR so going to approve this ✅ 🎉  If you want to address this here, absolutely feel free to, but I believe [there is ongoing discussion](https://github.com/slack-samples/deno-github-functions/pull/21#pullrequestreview-1398381160) on this topic since this error is somewhat unexpected.

The only comment I left is a question on the custom error handling, just to make sure things are all matching. Feel free to merge after addressing this – whatever the answer may be. Thanks again for all of these improvements! 👏

2023-04-28 01:31 UTC, e-zim commented on functions/configure_events.ts
> +    return { error: `${err.error}` };
Should this `catch` follow a similar pattern as this one above?

https://github.com/slack-samples/deno-simple-survey/blob/b8f4682c45291aca8769c18743dde2c32b44bff5/functions/configure_events.ts#L40-L45

2023-04-28 19:09 UTC, WilliamBergamin commented on functions/configure_events.ts
> +    return { error: `${err.error}` };
Ohh yess good catch 💯

2023-04-28 19:13 UTC, WilliamBergamin commented on functions/configure_events.ts
> +    return { error: `${err.error}` };
Maybe adding unit tests to the sample could help prevent these types of things

2023-04-28 20:22 UTC, e-zim approved these changes
Appreciate those recent changes! All of the code looks great to me, so will give my approval here ✅ 🏆 

With the most changes to the external auth section of the README, I want to check with @misscoded before we make the merge. The content seems good to me, but I'm not sure if we have standardized this section? For reference, slack-samples/deno-github-functions#23 makes similar changes (and has not yet been merged, so can be updated to match whatever's decided).

2023-05-01 17:26 UTC, misscoded commented
@e-zim @WilliamBergamin If the two projects put forth the same content, they should match. Whichever takes precedence I leave up to the two of you!

2023-05-01 18:46 UTC, WilliamBergamin commented
@e-zim @misscoded I think the implementation of the `Add your GitHub Client ID` section in https://github.com/slack-samples/deno-github-functions/pull/23 is clearer, I've modified this PR to match it

2023-05-01 18:48 UTC, merged